In [2]:
import torch

### Construct a 5X3 matrix and intialize to 0 and dtype long:

In [25]:
x = torch.zeros(5 , 3, dtype = torch.long) 
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### Construct a randomly intialized matrix

In [21]:
x = torch.rand(2,3)
x

tensor([[0.8683, 0.4974, 0.3153],
        [0.3860, 0.0767, 0.8641]])

### Construct a tensor directly from data

In [26]:
x = torch.tensor([5, 3])
x


tensor([5, 3])

### Create a tensor from an existing tensor

In [30]:
x = x.new_ones(5, 3 , dtype = torch.float)
print(x)

y = torch.rand_like(x, dtype= torch.double)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[0.8181, 0.0275, 0.1930],
        [0.0156, 0.3152, 0.9998],
        [0.5532, 0.4546, 0.1049],
        [0.6575, 0.9631, 0.5918],
        [0.1400, 0.7764, 0.4646]], dtype=torch.float64)

### Get it's size
size() is a tuple , so it supports all tuple operations. 

In [37]:
x.size()

5

### Addition

In [38]:
torch.add(x, y)

tensor([[1.8181, 1.0275, 1.1930],
        [1.0156, 1.3152, 1.9998],
        [1.5532, 1.4546, 1.1049],
        [1.6575, 1.9631, 1.5918],
        [1.1400, 1.7764, 1.4646]], dtype=torch.float64)

In [39]:
print(x + y)

tensor([[1.8181, 1.0275, 1.1930],
        [1.0156, 1.3152, 1.9998],
        [1.5532, 1.4546, 1.1049],
        [1.6575, 1.9631, 1.5918],
        [1.1400, 1.7764, 1.4646]], dtype=torch.float64)


### Providing an output tensor as argument

In [43]:
result = torch.empty_like(x)
torch.add(x, y, out=result)
result

tensor([[1.8181, 1.0275, 1.1930],
        [1.0156, 1.3152, 1.9998],
        [1.5532, 1.4546, 1.1049],
        [1.6575, 1.9631, 1.5918],
        [1.1400, 1.7764, 1.4646]])

### Additon: in-place
Any operation that mutates a tensor in-place is post-fixed with an _. 

In [44]:
y.add_(x)
y

tensor([[1.8181, 1.0275, 1.1930],
        [1.0156, 1.3152, 1.9998],
        [1.5532, 1.4546, 1.1049],
        [1.6575, 1.9631, 1.5918],
        [1.1400, 1.7764, 1.4646]], dtype=torch.float64)

### Resizing: If you want to resize/reshape tensor , use torch.view()

In [59]:
x = torch.randn(4,4)
print('x\n', x)
y = x.view(16)
print("y\n", y)
z = x.view(-1, 8)
print("z\n", z)

# Let's check the size
print("\n x size: %s  | y size: %s |  z size: %s" %(x.size(), y.size(), z.size()))

x
 tensor([[-0.1079, -0.5550, -0.7345, -1.4636],
        [-0.4098,  0.9465, -0.0841,  0.7147],
        [-1.7593,  0.1193, -2.0751, -0.4176],
        [ 0.0455, -1.1473,  0.8559, -0.5326]])
y
 tensor([-0.1079, -0.5550, -0.7345, -1.4636, -0.4098,  0.9465, -0.0841,  0.7147,
        -1.7593,  0.1193, -2.0751, -0.4176,  0.0455, -1.1473,  0.8559, -0.5326])
z
 tensor([[-0.1079, -0.5550, -0.7345, -1.4636, -0.4098,  0.9465, -0.0841,  0.7147],
        [-1.7593,  0.1193, -2.0751, -0.4176,  0.0455, -1.1473,  0.8559, -0.5326]])

 x size: torch.Size([4, 4])  | y size: torch.Size([16]) |  z size: torch.Size([2, 8])


## Numpy bridge

In [67]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [68]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [69]:
# Note b changes it's value
a = a.add_(1)
b

array([2., 2., 2., 2., 2.], dtype=float32)

### Converting numpy to tensor


In [70]:
import numpy as np

In [74]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
